language: python
python:
- '3.6'
script:
- sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
  user: cseelye
  password:
    secure: UJ3sP/1JMpakTLN0b2UkioD4B3bi8Rx9NLNQDpRk9BUw5iOw2cQ0B5tfAkSPGxJ/aVYGv9JtRVyvZbmU/rKgOhrBlUdTKJ44wFhgpFBvGLegWBRg1pjgeDM94EsdSC0skrqf7xOCg5pHs4W3giMbaMdOocfwSleDmSsu0CQRYjLpC0x2+d6Nwkxy3fj0XTgwHQcTjr/ugLQRsaT3e/cIcy/17J6xMIp2t+7sgNLR8t60Bf+hqyw2qUj6H1kwUM2rlWR6LpbLwKp6t46CI9Fsjg8fKE6wB9oyPQQqN5bGM170YaqhRHmXCqh/qPb6+h5ZC3eCWqK48VBtsjJhWXkhI6a+uRHjgkZqyTco/dlN/BPGTsClvRszNuy2iTNI/4peIqUmI7JqtukbhiU6TkBupwbrJFxw4OZ7j5VhComzubwqNav+xmbGS+srmdBAs8tEPU2lb3NzaEMi91NSAyGdnAziNujv0N5RhK2cj8wuZIKd6EFUJYmyPwuGt26F68/eQ6FjN9YZzAhfZ/QBIfD2/toBs+h3PzNhUZa93bl8HklrnlbvRbJD6LgaiIsgPBsd/tU5dENP/X0S4uovQrV96TBPwg9XBBMSN0mF+xUqphTGPI6Dc3gN4QmLTXE/i0SZpZdcWI71ZaHpxoeMlUcWK9hkcrX4DEXoc5p90JDO14k=
